# Generated by Django 2.0.4 on 2018-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_type',
            field=models.CharField(choices=[('Concert', 'Concert'), ('Party', 'Party'), ('Seminar', 'Seminar'), ('Sports', 'Sports'), ('Gaming', 'Gaming'), ('Other', 'Other')], default='other', max_length=10),
        ),
    ]
