# Generated by Django 2.0.4 on 2018-04-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180416_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_image/profile_image/user.jpg', upload_to='profile_image'),
        ),
    ]
